blank_issues_enabled: false
contact_links:
  - name: "Ask a question"
    url: "https://stackoverflow.com/questions/tagged/evernaut"
    about: "Ask a question on Stack Overflow (use the #evernaut and #[repository-name] tags)"
