version: 1
update_configs:
  - default_labels:
      - "Type: Automated"
    directory: "/"
    package_manager: "javascript"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
